context

diff --git a/.github/workflows/onPushToMain.yml b/.github/workflows/onPushToMain.yml
--- a/.github/workflows/onPushToMain.yml
+++ b/.github/workflows/onPushToMain.yml
@@ -50,9 +50,9 @@ jobs:
             git commit -am "chore: update README.md"
             git push -u origin ${{ github.ref_name }}
           fi
-      - name: Failure
-        run: |
-          exit 1
+      # - name: Failure
+      #   run: |
+      #     exit 1
       - name: Create Github Release
         uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda #v2.2.1
         if: ${{ steps.version-check.outputs.skipped == 'false' }}
